version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "workflows"
    labels:
      - "workflows"
      - "automated-update"

  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/" # location of package.json and package-lock.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "automated-update"
