name: End-to-end tests
on:
  push:
    branches:
      - feature/aqa-865
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5

#TODO enable if secrets are needed
#      - name: Decrypt secrets file
#        run: .github/decrypt_secret.sh
